apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    source-url: "https://github.com/org4rong/py3src"
    source-revision: "dcd8cd91135c2c5f33fc913a1d99b8f363fd06a0"
  name: py3svc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3img:dcd8cd91135c2c5f33fc913a1d99b8f363fd06a0@sha256:56bf78638850d97addf3514a1a6844fafee6434dd55f5d0b0e692074abd062b4
          name: container-image
