apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    git_url: "https://github.com/org4rong/py3src"
    git_rev: "cc1932ead826747fd70dd7d3a9c3fc8c0c6d82e8"
  name: py3svc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3img:cc1932ead826747fd70dd7d3a9c3fc8c0c6d82e8@sha256:1a12fed228133e5d5edcd81e2d72778c03104c59d4a712c6181278f492cbc676
          name: container-image
