apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    source-url: "https://github.com/org4rong/py3src"
    source-revision: "306b60ee7074b7aabf45ed0f0a184d8919f663fa"
  name: py3svc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3img:306b60ee7074b7aabf45ed0f0a184d8919f663fa@sha256:58d95a72c8f8df5e6940eeaaa74a2bec682772efa192563f58802d384989d9c1
          name: container-image
