apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: py3svc-gitops
  description: This is GitOps manifest for py3svc   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: py3svc
    backstage.io/kubernetes-id: py3svc 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: py3svc   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:py3svc
