apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: py3svc
  janus-idp.io/tekton: py3svc
  backstage.io/kubernetes-id: py3svc
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py3svc
resources:
- deployment.yaml
- route.yaml
- service.yaml
