apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    source-url: "https://github.com/org4rong/py3src"
    source-revision: "393811a76d70662a0fa4bcc259222ec01a0c8a4b"
  name: py3svc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3img:3fafc877d7ce5c354f787d73fccd9156bc21240e@sha256:1164e36b372ed5adc888bbdda50a291a4d3ef32736dc12fa6bdf036022f06da1
          name: container-image
