apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: py3svc-gitops-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/webchang/tssc-sample-templates/refs/heads/main/concert-gitops-push-rhtap.yaml"
    pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/v1.4.x/pac/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/webchang/tssc-sample-templates/refs/heads/main/concert-upload-cd.yaml"
  labels:
    argocd/app-name: py3svc
    janus-idp.io/tekton: py3svc
    backstage.io/kubernetes-id: py3svc
    backstage.io/kubernetes-namespace: rhtap-app
    app.kubernetes.io/part-of: py3svc
spec:
  params:
    - name: git-url
      value: '{{repo_url}}'
    - name: revision
      value: '{{revision}}'
    - name: target-branch
      value: '{{target_branch}}'
    - name: event-type
      value: '{{event_type}}'
    - name: if-concert-enabled
      description: Optional Concert enablement setting for generating and uploading ConcertDef files.  Default is "false".
      value: "true"
    - name: concert-component-version
      description: Optional Concert setting for the ConcertDef component version.  Default is "1.0.0".
      value: "1.0.0"
    - name: concert-api-base
      description: Optional Concert setting for the base DOMAIN of the API service.  When the value is not set or is an empty string, it will be "{serviceName.nameSpace.svc}" per the Kubernetes service name and namespace in use.
      value: "apps.rhocp2.hcp.res.ibm.com"
    - name: concert-api-exposure
      description: Optional Concert setting for the API exposure.  Default is "private".
      value: "public"
  pipelineRef:
    name: gitops-push
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: concert-api
      secret:
        secretName: concert-api
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
